name: Test Package CRUD

on:
  push:
    branches:
      - "*"

jobs:
  pullDB:
    runs-on: ubuntu-latest
    steps:
      - name: MongoDB in GitHub Actions
        uses: supercharge/mongodb-github-action@1.11.0
        with:
          mongodb-db: test

  runtest:
    runs-on: ubuntu-latest
    needs: pullDB
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: npm ci
      - run: npm run build
      - run: npm test
